config:
  configFile: |-
    provider="github"
    github_org="shoal-konst-fish"
    http_address="0.0.0.0:4180"
    upstreams="file:///dev/null"
    email_domains=["*"]
    skip_provider_button = true
    cookie_domains=["sso.konst.fish"]
    whitelist_domains=[".konst.fish:*"]

ingress:
  enabled: true
  className: nginx
  hosts:
    - sso.konst.fish
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-dns"
    external-dns.alpha.kubernetes.io/hostname: "sso.konst.fish"
  tls:
    - secretName: oauth-tls
      hosts:
        - sso.konst.fish

sessionStorage:
  type: redis
  redis:
    existingSecret: oauth2-proxy-redis
    standalone:
      connectionUrl: redis://oauth2-proxy-redis-headless:6379

redis:
  enabled: true
  architecture: standalone
  master:
    persistence:
      enabled: false

metrics:
  enabled: true
  serviceMonitor:
    enabled: true