---

- name: Debug extra_server_args
  debug:
    var: extra_server_args

- name: Debug api_endpoint
  debug:
    var: api_endpoint

# apt update
- name: Update apt cache
  apt:
    update_cache: "yes"

- name: Install git
  apt:
    name: git
    state: present

- name: Install zsh
  apt:
    name: zsh
    state: present

- name: Install nfs-common
  apt:
    name: nfs-common
    state: present

- name: Install cifs-utils
  apt:
    name: cifs-utils
    state: present

- name: Install open-iscsi
  apt:
    name: open-iscsi
    state: present

# wheel
- name: Make sure we have a 'wheel' group
  group:
    name: wheel
    state: present

- name: Allow 'wheel' group to have passwordless sudo
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: "^%wheel"
    line: "%wheel ALL=(ALL) NOPASSWD: ALL"
    validate: "visudo -cf %s"

- name: Add the user {{ user_name }}
  user:
    name: "{{ user_name }}"
    shell: /bin/zsh
    groups: sudo,wheel
    append: yes

- name: Set login shell of user {{ user_name }} to `/bin/zsh` with `usermod`
  command: usermod --shell /bin/zsh {{ user_name }}
  become: true
  changed_when: false

- name: Set login shell of user root to `/bin/zsh` with `usermod`
  command: usermod --shell /bin/zsh root
  become: true
  changed_when: false

- name: Set SSH key for {{ user_name }} from GitHub
  authorized_key:
    user: "{{ user_name }}"
    state: present
    key: https://github.com/{{ github_user }}.keys

# zsh 
- name: Create .zsh directory for {{ user_name }}
  file:
    path: /home/{{ user_name }}/.zsh
    state: directory

- name: Clone spaceship-prompt repo for {{ user_name }}
  ansible.builtin.git:
    repo: https://github.com/spaceship-prompt/spaceship-prompt.git
    dest: /home/{{ user_name }}/.zsh/spaceship
    version: master
    depth: 1

- name: Add spaceship-prompt to zshrc for {{ user_name }}
  ansible.builtin.lineinfile:
    path: /home/{{ user_name }}/.zshrc
    line: source "$HOME/.zsh/spaceship/spaceship.zsh"
    create: yes

# nfs
- name: Mount NFS Share
  ansible.posix.mount:
    src: 10.0.1.1:/mnt/md0/stor
    path: /stor
    opts: rw,bg,hard,nointr,rsize=32768,wsize=32768,tcp,timeo=600
    state: mounted
    fstype: nfs
  when: inventory_hostname in groups.get('guppy', [])
